Thinkmill/manypkg

.changeset/curly-boxes-promise.md
README.md

Resolves #44 
Add reference to `manypkg exec` to readme

#44: Add reference to `manypkg exec` to readme

---

.changeset/tricky-olives-admire.md
.gitignore
__fixtures__/local-deps-cycle/package.json
__fixtures__/local-deps-cycle/packages/cyclic-dep/package.json
packages/get-packages/src/index.test.ts
packages/get-packages/src/index.ts

Unfortunately, `gitignore` option gets resolved **after** globbing - whereas `ignore` patterns are taken into account when globbing.

Fix the cyclic dep fix

---

.changeset/real-plums-wave.md
__fixtures__/basic-lerna/lerna.json
__fixtures__/basic-lerna/package.json
__fixtures__/basic-lerna/packages/package-one/package.json
__fixtures__/lerna-workspace-base/lerna.json
__fixtures__/lerna-workspace-base/package.json
__fixtures__/lerna-workspace-base/packages/pkg-a/package.json
__fixtures__/lerna-workspace-base/packages/pkg-b/package.json
packages/cli/src/index.ts
packages/find-root/src/index.test.ts
packages/find-root/src/index.ts
packages/get-packages/src/index.test.ts
packages/get-packages/src/index.ts

Howdy! 👋 
I like the level of abstraction of these packages, and wanted to make them useful for folks using Lerna monorepo patterns.
Thanks!

feat: Add support for Lerna monorepos

---

.changeset/little-gifts-tickle.md
packages/cli/src/checks/INCORRECT_REPOSITORY_FIELD.ts
packages/cli/src/checks/__tests__/INCORRECT_REPOSITORY_FIELD.ts
packages/cli/src/checks/__tests__/INTERNAL_MISMATCH.ts
packages/cli/src/checks/__tests__/INVALID_DEV_AND_PEER_DEPENDENCY.ts
packages/cli/src/checks/utils.ts
packages/cli/src/index.ts
packages/cli/src/test-helpers.ts

My repositories use `main` as the default branch, which causes `manypkg check` to incorrectly error with:
```
$ yarn manypkg check
...
☔️ error @example/button has a repository field of "https://github.com/example/repo/tree/main/button" when it should be "https://github.com/example/repo/tree/master/button"
error Command failed with exit code 1.
```
With this new cli swich, I can successfully execute:
```
$ yarn manypkg check --default-branch=main
...
✨  Done in 0.15s.
```

Add --default-branch cli switch for INCORRECT_REPOSITORY_FIELD check

---

.changeset/rude-lizards-rule.md
packages/gatsby-source-workspace/package.json
packages/get-packages/package.json

Running an audit on one of my projects flagged this field as missing for these packages.

Add missing license fields

---

.changeset/calm-eyes-listen.md
packages/cli/package.json
yarn.lock

This fixes a security vulnerability in `yargs-parser` transitive dependency :)

Bump meow to ^6.0.0

---

.changeset/dirty-phones-tell.md
README.md
__fixtures__/basic-with-scripts/packages/package-two-one/package.json
packages/cli/README.md
packages/cli/src/__snapshots__/run.test.ts.snap
packages/cli/src/run.test.ts
packages/cli/src/run.ts

This PR closes #82 by adding functionality for targeting a project using the exact package or directory name:
`@project/package-a` at `packages/pkg-a`
`@project/package-a-1` at `packages/pkg-a-1`
```bash
yarn manypkg run @project/package-a start
yarn manypkg run packages/pkg-a
```

feat(cli): add exact pkg/dir name matching for run command

---

README.md

the headers structure for the rules seems irregular and it made it trickier to read, so i set them all to the initial headers structure used for the firs two rules. would you agree that it's harder to see the separation between rules when using h3/h4?
Other ideas to improve readability:
- blockquote the rule description to make it stand out?
- using the collapsing markdown sections GFM supports? doesn't work on npm though?

header structure for rules in the README

---

.changeset/calm-fishes-search.md
packages/cli/package.json
yarn.lock

Removes package `meow` from `@manypkg/cli`. The `meow` package contains a vulnerable package `hosted-git-info@2.8.8`
Introduced through: `@manypkg/cli@0.17.0 › meow@6.1.1 › normalize-package-data@2.5.0 › hosted-git-info@2.8.8`
More info here: https://app.snyk.io/test/npm/@manypkg/cli/0.17.0#SNYK-JS-HOSTEDGITINFO-1088355
It appears to me that `meow` is not used anywhere in the codebase so it made sense to remove this package rather than upgrade it to a safe version.

Remove vulnerable package meow

---

packages/get-packages/package.json
yarn.lock

This package imports a type from a file not defined in the package.
https://github.com/Thinkmill/manypkg/blob/24cf58240d8312c050c17708fb0b7e8aad78d21b/packages/get-packages/src/index.ts#L9
May I suggest including `depcheck` to avoid this in the future?

chore: incorrect type defs

---

.changeset/fair-days-rest.md
__fixtures__/pnpm-exclude-workspace-case/package.json
__fixtures__/pnpm-exclude-workspace-case/packages/pkg-a/package.json
__fixtures__/pnpm-exclude-workspace-case/packages/pkg-b/package.json
__fixtures__/pnpm-exclude-workspace-case/packages/pnpm-exclude-workspace-case/package.json
__fixtures__/pnpm-exclude-workspace-case/pnpm-workspace.yaml
packages/get-packages/src/index.test.ts
packages/get-packages/src/index.ts

fix(pnpm): absolute cwd path matched workspace exclude rules (#121)

---

.changeset/olive-frogs-fly.md
packages/cli/package.json

- `@manypkg/cli` > `get-workspaces@^0.6.0` > `globby@^9.2.0` has [high severity vulnerability](https://github.com/advisories/GHSA-ww39-953v-wcq6).
- `@manypkg/cli` doesn't use `get-workspaces` since [v0.12.0](https://github.com/Thinkmill/manypkg/blob/master/packages/cli/CHANGELOG.md#0120), #51.
- Related issue: #105

fix: remove unused get-workspaces from @manypkg/cli

---

.prettierrc.js
package.json
packages/cli/package.json
packages/find-root/package.json
packages/gatsby-source-workspace/README.md
packages/gatsby-source-workspace/package.json
tsconfig.json
yarn.lock

- Move _prettier config_ into Prettier's dedicated config file, for ease of discovery
- Add the `prettier-plugin-packagejson` prettier plugin
- Turn off `useUnknownInCatchVariables` typescript rule
I am open to pushback on this, but I think in general, using `package.json` as an unstructured grab-bag is less discoverable than using tool-specific configuration files. So I was hoping to split out `.prettierrc.js` into its own file in the root.
It would also be nice to add `prettier-plugin-packagejson` -- it's very opinionated, as it wraps the opinionated `sort-package-json` utility, but I've found it really nice to just give in and let VSCode auto-sort my whole packagejson every time I touch it.
Last, I think we (and everyone else) should turn off `useUnknownInCatchVariables`. Notably, even …

Suggested fixes to tsconfig, prettier config

---

.changeset/rude-squids-switch.md
__fixtures__/bolt-workspace/package.json
__fixtures__/bolt-workspace/packages/pkg-a/package.json
__fixtures__/bolt-workspace/packages/pkg-b/package.json
packages/cli/README.md
packages/cli/src/utils.ts
packages/find-root/README.md
packages/find-root/src/index.ts
packages/get-packages/README.md
packages/get-packages/src/index.test.ts
packages/get-packages/src/index.ts
packages/tools/src/BoltTool.ts
packages/tools/src/index.ts

This addresses #172 by reverting #165, with some minor modifications that I've annotated in comments.

Restore support for Bolt monorepos

---

.changeset/node-types-lag.md
packages/find-root/package.json
yarn.lock

`@types/node` should not be a dependency for `find-root` since it doesn't expose any of the node types in its API, so I've moved it to a dev dep. I also updated the version to the last Node 16 types version. I chose Node 16 as it's [the same version used in CI](https://github.com/Thinkmill/manypkg/blob/main/.github/workflows/main.yml#L19).
Fixes #118.

Update and move `@types/node` to dev updates

---

.changeset/clever-cherries-count.md
package.json
packages/cli/package.json
packages/cli/src/upgrade.ts
yarn.lock

Fixes: #180 
package-json went ESM-only, but we only use it in one place in upgrade.ts, and the error that was thrown told me to use a dynamic import, so I did. It was already an `async` context, so I think this is fine?
The tests pass!
Many yarn.lock updates though!

Updated `package-json` dependency

---

.changeset/chatty-pillows-enjoy.md
packages/cli/src/checks/INTERNAL_MISMATCH.ts
packages/cli/src/checks/__tests__/INTERNAL_MISMATCH.ts

fix: allow tags in `npm:x`-deps

---

.changeset/breezy-readers-chew.md
packages/get-packages/src/index.test.ts
packages/get-packages/src/index.ts

Fixes #200
This PR updates `getPackages` to start looking from the monorepo root, instead of the passed `dir`

Fix start directory for `getPackages`

---

.changeset/weak-icons-invent.md
packages/cli/src/upgrade.ts

Running `manypkg upgrade @scope` currently upgrades packages formatted as `@scope/package` and `@scope-extra/package`. This is problematic because it should not be updating `@scope-extra/` packages.
Properly upgrade package so `manypkg upgrade @scope` only upgrades `@scope/` packages and `manypkg upgrade @scope-extras` only upgrades `@scope-extras/` packages.
- Addresses #148
- Fixes the PR changes requested in #175

Fix Upgrade to Properly Update Scoped Packages

---

.changeset/mean-nails-hide.md
packages/find-root/package.json
packages/gatsby-source-workspace/package.json
packages/get-packages/package.json
packages/tools/package.json

The other packages had it already, but these were missing it

Add git repository info to package.json

---

README.md

This PR adds a Configuration section to `README.md` which documents `manypkg` configuration in the root `package.json`.
It also adds a "Key" to each rule in the Checks section which is the value users need to add to `manypkg.ignoredRules` to ignore that rule.
Closes #178

add configuration documentation to README.md

---

.changeset/cool-goats-kiss.md
packages/find-root/package.json
packages/find-root/src/index.ts

it's a relatively simple piece of functionality, so probably don't need 6 dependencies for it
https://npmgraph.js.org/?q=find-up@4.1.0

remove find-up to remove six dependencies

---

.changeset/curvy-garlics-exercise.md
packages/tools/package.json
packages/tools/src/PnpmTool.ts
yarn.lock

Replaces https://npmgraph.js.org/?q=read-yaml-file@1.1.0 with https://npmgraph.js.org/?q=js-yaml
`read-yaml-file` barely does anything and is just tiny wrapper around `js-yaml` that calls `strip-bom`. However, `strip-bom` is unnecessary as `js-yaml` now strips the bom character by itself: https://github.com/nodeca/js-yaml/blob/0d3ca7a27b03a6c974790a30a89e456007d62976/lib/loader.js#L1665

remove six yaml-related dependencies

---

.changeset/angry-houses-kiss.md
packages/tools/package.json
packages/tools/src/expandPackageGlobs.ts
yarn.lock

https://npmgraph.js.org/?q=globby - 23 dependencies
https://npmgraph.js.org/?q=fast-glob - 17 dependencies

switch to `fast-glob` to remove 6 dependencies

---

.changeset/thick-panthers-smile.md
package.json
packages/cli/package.json
packages/cli/src/utils.ts

For #221 - removes 4 dependencies

[dependencies-replacement] Replace fs-extra with node:fs/promises

---

.changeset/spotty-planets-grin.md
packages/cli/package.json
yarn.lock

Removes transitive dependency on `builtins` package. Version `5.0.1` is the last one with node 14 support in its `engines` field, even though `6.0.0` has the exact same source-code :-/
references #221

[dependencies-replacement] Update validate-npm-package-name to 5.0.1, removing one subdependency

---

babel.config.js

Turns out, @Andarist was correct in https://github.com/Thinkmill/manypkg/pull/231#discussion_r1804429503 - because babel was updated, this setting is not needed.

Revert unnecessary change to babel config

---

.changeset/chilly-bottles-eat.md
.changeset/chilly-moles-grow.md
packages/find-root/src/index.test.ts
packages/find-root/src/index.ts
packages/get-packages/src/index.ts
packages/tools/src/Tool.ts

closes https://github.com/Thinkmill/manypkg/issues/219

feat: serializable return values

---

.changeset/curly-mirrors-own.md
README.md
packages/cli/src/index.ts

closes #91 
This is a breaking change.

Change defaultBranch default to main

---

.changeset/ten-moose-clean.md
README.md
__fixtures__/basic-bun-json-lock/bun.lock
__fixtures__/basic-bun-json-lock/package.json
__fixtures__/basic-bun-json-lock/packages/package-one/package.json
__fixtures__/basic-bun-json-lock/packages/package-one/src/index.js
__fixtures__/basic-bun/bun.lockb
__fixtures__/basic-bun/package.json
__fixtures__/basic-bun/packages/package-one/package.json
__fixtures__/basic-bun/packages/package-one/src/index.js
__fixtures__/bun-no-lock/package.json
__fixtures__/bun-no-lock/packages/package-one/package.json
__fixtures__/bun-workspace-base/bun.lockb
__fixtures__/bun-workspace-base/package.json
__fixtures__/bun-workspace-base/packages/pkg-a/package.json
__fixtures__/bun-workspace-base/packages/pkg-b/package.json
packages/cli/README.md
packages/cli/src/utils.ts
packages/find-root/README.md
packages/find-root/src/index.test.ts
packages/find-root/src/index.ts
packages/get-packages/README.md
packages/get-packages/src/index.test.ts
packages/tools/src/BunTool.ts
packages/tools/src/index.ts

- **BunTool Implementation:**  
Added a new `BunTool` for detecting and working with Bun-based monorepos.
- **Lockfile Support:**  
Supports both `bun.lockb` (binary) and `bun.lock` (JSON) lockfile formats for Bun.
- **Monorepo Detection:**  
Integrates Bun detection into the monorepo tool system, allowing Bun monorepos to be recognized alongside Yarn, npm, pnpm, Lerna, and Rush.
- **CLI Integration:**  
Updates the CLI to handle Bun package management commands (e.g., `bun install`), ensuring commands like `manypkg check`, `manypkg fix`, and `manypkg run` work seamlessly in Bun monorepos.
- **Test Coverage:**  
Adds comprehensive tests and fixtures for Bun monorepos, including detection, package resolution, and lockfile handling.
- Updates documentation and READMEs to mention Bun support. …

Add Bun Support to manypkg
